language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
matrix:
  allow_failures:
    - node_js: "0.11"

# Upgrade npm to fix node@0.8
before_install:
  - npm install npm@latest -g

notifications:
  email: false
